// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrL9OgF5hHg594z4wQGYDYl8LlEPSwYmU',
    appId: '1:346305292576:web:9a5a6d8832efc30b9f4f45',
    messagingSenderId: '346305292576',
    projectId: 'little-flower-app',
    authDomain: 'little-flower-app.firebaseapp.com',
    storageBucket: 'little-flower-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJYKHn6avWVQQjErYBWaEuXFu0nuTv9BA',
    appId: '1:346305292576:android:92233c49b5ad76a29f4f45',
    messagingSenderId: '346305292576',
    projectId: 'little-flower-app',
    storageBucket: 'little-flower-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKV8f34h_8cbD9FZId-748L4D2MX5YWME',
    appId: '1:346305292576:ios:d58d1683a2f43c4c9f4f45',
    messagingSenderId: '346305292576',
    projectId: 'little-flower-app',
    storageBucket: 'little-flower-app.firebasestorage.app',
    iosBundleId: 'com.example.littleFlowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKV8f34h_8cbD9FZId-748L4D2MX5YWME',
    appId: '1:346305292576:ios:d58d1683a2f43c4c9f4f45',
    messagingSenderId: '346305292576',
    projectId: 'little-flower-app',
    storageBucket: 'little-flower-app.firebasestorage.app',
    iosBundleId: 'com.example.littleFlowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrL9OgF5hHg594z4wQGYDYl8LlEPSwYmU',
    appId: '1:346305292576:web:70e999f722981eb39f4f45',
    messagingSenderId: '346305292576',
    projectId: 'little-flower-app',
    authDomain: 'little-flower-app.firebaseapp.com',
    storageBucket: 'little-flower-app.firebasestorage.app',
  );
}
